branch-defaults:
  master:
    environment: Junweb-env
global:
  application_name: JunWeb
  default_ec2_keyname: JunWeb
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: Hibagon
  sc: git
  workspace_type: Application
