branch-defaults:
  master:
    environment: Junweb-env
global:
  application_name: JunWeb
  default_region: ap-northeast-1
  include_git_submodules: true
  profile: Hibagon
  sc: git
  workspace_type: Application
